#!/bin/bash
# Tests for check-ai-attribution.sh: each case pipes a message in and asserts the verdict.
set -uo pipefail

cd "$(dirname "$0")/.."
failures=0

expect() {
  local want="$1" message="$2"
  if printf '%s\n' "$message" | ./scripts/check-ai-attribution.sh >/dev/null 2>&1; then got=clean; else got=blocked; fi
  if [ "$got" != "$want" ]; then
    echo "FAIL: expected $want, got $got for: $message"
    failures=$((failures + 1))
  fi
}

expect blocked "Fix bug

Co-Authored-By: Claude <noreply@anthropic.com>"
expect blocked "co-authored-by: Codex <codex@openai.com>"
expect blocked "🤖 Generated with [Claude Code](https://claude.com/claude-code)"
expect blocked "Generated by Codex"
expect blocked "This change was written with ChatGPT."
expect blocked "Authored by an AI assistant"
expect blocked "Created using GitHub Copilot"

expect clean "Bump CodeQL actions to v4.38.1 together"
expect clean "Co-Authored-By: Jane Doe <jane@example.com>"
expect clean "Document the Claude and Codex harness setup"
expect clean "Add AI tutor provider chain (Gemini, OpenRouter)"
expect clean "Generated OpenAPI client from the spec"

if [ "$failures" -gt 0 ]; then
  echo "check-ai-attribution: $failures test(s) failed"
  exit 1
fi
echo "check-ai-attribution: all tests passed"
